language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_script:
  - cd TestSpring/
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r TestSpring
  - mkdir -p deploy
  - mv TestSpring.zip deploy/TestSpring.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY AKIA3CHWVKLTNYMBODNR
    secret_access_key: $AWS_SECRET_KEY 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
    bucket: springboot-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ejhjjp11@naver.com
